base/urls.py
from django.urls import path
from .views import *

app_name = 'base'

urlpatterns = [
    path('', index, name='index'),
    path('about/', about, name='about'),
    path("set_language/<str:language>", set_language, name="set-language"),
]

blog/urls.py
from django.urls import path
from .views import *

app_name = 'blog'

urlpatterns = [
    path('', blogs, name='blogs'),
    path('<slug:blog_slug>', blog_details, name='blog_details'),
]

contact/urls.py
from django.urls import path
from .views import *

app_name = 'contact'

urlpatterns = [
    path('', contact, name='contact'),
]

core/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += i18n_patterns(
    path('', include('base.urls', namespace='base')),
    path('rooms/', include('room.urls', namespace='room')),
    path('services/', include('service.urls', namespace='service')),
    path('blogs/', include('blog.urls', namespace='blog')),
    path('contact/', include('contact.urls', namespace='contact')),
    path('user/', include('user.urls', namespace='user')),
    path('rosetta/', include('rosetta.urls')),
    prefix_default_language=False,
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

room/urls.py
from django.urls import path
from .views import *

app_name = 'room'

urlpatterns = [
    path('', rooms, name='rooms'),
    path('<slug:room_slug>/', room_details, name='room-details')
]

user/urls.py
from django.urls import path
from .views import *

app_name = 'user'

urlpatterns = [
    path('login/', login_view, name='login'),
    path('register/', register, name='register'),
    path('logout/', logout_view, name='logout'),
    path('account/', account, name='account'),
    path('change-password/', change_password, name='change-password'),
    path('payment/', payment, name='payment'),
    path('send-email-code/', send_email_code, name='send-email-code'),
    path('six-digit-password/', six_digit_password, name='six-digit-password'),
]

base/models.py
from django.db import models

class NavigationItem(models.Model):
    title = models.CharField(max_length=100)
    navbar_img = models.ImageField(upload_to='navbar_img/')
    footer_img = models.ImageField(upload_to='footer_img/')
    phone = models.CharField(max_length=50)
    email = models.EmailField()
    address = models.TextField()
    facebook_link = models.URLField(max_length=200, blank=True, null=True)
    instagram_link = models.URLField(max_length=200, blank=True, null=True)
    twitter_link = models.URLField(max_length=200, blank=True, null=True)
    telegram_link = models.URLField(max_length=200, blank=True, null=True)
    whatsapp_number = models.CharField(max_length=200, blank=True, null=True)
    tiktok_link = models.URLField(max_length=200, blank=True, null=True)
    youtube_link = models.URLField(max_length=200, blank=True, null=True)
    map_link = models.URLField(max_length=400, blank=True, null=True)

    def __str__(self):
        return self.title

class HomeHotel(models.Model):
    title = models.CharField(max_length=100)
    content = models.CharField(max_length=200)
    image = models.ImageField(upload_to='home_hotel_img/')
    resp_image = models.ImageField(upload_to='home_hotel_resp_img/')
    star_number = models.IntegerField()
    owner_phone_number = models.CharField(max_length=50)

    def __str__(self):
        return self.title
      
class Brand(models.Model):
    name = models.CharField(max_length=100)
    image = models.ImageField(upload_to='brand_img/')

    def __str__(self):
        return self.name    

class About(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    image = models.ImageField(upload_to='about_img/')
    customer_count = models.IntegerField()

    def __str__(self):
        return self.title
    
    class Meta:
        verbose_name_plural = 'About'      
        
class Mission(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    image = models.ImageField(upload_to='mission_img/')
    video_url = models.CharField(max_length=400)

    def __str__(self):
        return self.title  
    
class FAQ(models.Model):
    question = models.CharField(max_length=200)
    answer = models.TextField()

    def __str__(self):
        return self.question
    
class Subscribe(models.Model):
    email = models.EmailField(unique=True, verbose_name="Email Ünvanı")

    def __str__(self):
        return self.email

base/forms.py
from django import forms
from .models import Subscribe

class SubscribeForm(forms.ModelForm):
    class Meta:
        model = Subscribe
        fields = ['email']
        widgets = {
            "email": forms.EmailInput(
                attrs={
                    "class": "form-control",
                    "placeholder": "Email ünvanınızı daxil edin",
                }
            )
        }

base/views.py
from django.shortcuts import render, redirect
from .models import HomeHotel
from .forms import SubscribeForm
from django.contrib import messages
from urllib.parse import urlparse
from django.conf import settings
from django.http import HttpResponseRedirect
from django.urls.base import resolve, reverse
from django.urls.exceptions import Resolver404
from django.utils import translation

def index(request):
    home_hotels = HomeHotel.objects.all()
    if request.method == "POST":
        form = SubscribeForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Uğurla abunə olundu!!!")
            return redirect('base:index')
    else:
        form = SubscribeForm()
        
    context = {
        'home_hotels': home_hotels,
        'form' : form
    }
    
    return render(request, 'index.html', context)

def about(request):
    return render(request, 'about.html')



def set_language(request, language):
    if language not in dict(settings.LANGUAGES):
        return HttpResponseRedirect("/")

    referer = request.META.get("HTTP_REFERER", "/")
    try:
        view = resolve(urlparse(referer).path)
        translation.activate(language)
        app_name = view.app_name if hasattr(view, 'app_name') else None
        view_name = f"{app_name}:{view.url_name}" if app_name else view.url_name

        response = HttpResponseRedirect(
            reverse(view_name, args=view.args, kwargs=view.kwargs)
        )
    except Resolver404:
        response = HttpResponseRedirect("/")
    
    response.set_cookie(settings.LANGUAGE_COOKIE_NAME, language)
    return response

templates/partials/_base.html
{% load static %}
{% load i18n %}

<!DOCTYPE HTML>
<html lang="az">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% trans "Quba Vadi" %} | {% block title %}{% endblock %}</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="index, follow">
    <meta property="og:title" content="">
    <meta property="og:description" content="">
    <meta property="og:image" content="">
    <meta property="og:url" content="">
    <meta name="twitter:card" content="">

    <link rel="icon" type="image/png" sizes="56x56" href="{% static 'assets/images/fav.png' %}">
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}" type="text/css" media="all">
    <link rel="stylesheet" href="{% static 'assets/css/owl.carousel.min.css' %}" type="text/css" media="all">
    <link rel="stylesheet" href="{% static 'assets/css/animate.css' %}" type="text/css" media="all">
    <link rel="stylesheet" href="{% static 'assets/css/animated-text.css' %}" type="text/css" media="all">
    <link rel="stylesheet" href="{% static 'assets/css/all.min.css' %}" type="text/css" media="all">
    <link rel="stylesheet" href="{% static 'assets/css/flaticon.css' %}" type="text/css" media="all">
    <link rel="stylesheet" href="{% static 'assets/css/theme-default.css' %}" type="text/css" media="all">
    <link rel="stylesheet" href="{% static 'assets/css/meanmenu.min.css' %}" type="text/css" media="all">
    <link rel="stylesheet" href="{% static 'assets/css/owl.transitions.css' %}" type="text/css" media="all">
    <link rel="stylesheet" href="{% static 'venobox/venobox.css' %}" type="text/css" media="all">
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap-icons.css' %}" type="text/css" media="all">
    <link rel="stylesheet" href="{% static 'assets/css/jquery.fancybox.min.css' %}" type="text/css" media="all">
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}" type="text/css" media="all">
    <link rel="stylesheet" href="{% static 'assets/css/responsive.css' %}" type="text/css" media="all">
    <link rel="stylesheet" href="{% static 'assets/css/scrollCue.css' %}" type="text/css" media="all">
    <link rel="stylesheet" href="{% static 'assets/css/dark.css' %}" type="text/css" media="all">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">
    <script src="{% static 'assets/js/vendor/modernizr-3.5.0.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'assets/css/swiper-bundle.css' %}">
    {% block css %} {% endblock %}

</head>
<body>

    {% include 'partials/_navbar.html' %}

    {% block content %} {% endblock %}

    {% include 'partials/_footer.html' %}

    <script src="{% static 'assets/js/vendor/jquery-3.6.2.min.js' %}"></script>
    <script src="{% static 'assets/js/popper.min.js' %}"></script>
    <script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'assets/js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'assets/js/jquery.counterup.min.js' %}"></script>
    <script src="{% static 'assets/js/waypoints.min.js' %}"></script>
    <script src="{% static 'assets/js/wow.js' %}"></script>
    <script src="{% static 'assets/js/imagesloaded.pkgd.min.js' %}"></script>
    <script src="{% static 'venobox/venobox.js' %}"></script>
    <script src="{% static 'assets/js/animated-text.js' %}"></script>
    <script src="{% static 'venobox/venobox.min.js' %}"></script>
    <script src="{% static 'assets/js/isotope.pkgd.min.js' %}"></script>
    <script src="{% static 'assets/js/jquery.meanmenu.js' %}"></script>
    <script src="{% static 'assets/js/jquery.scrollUp.js' %}"></script>
    <script src="{% static 'assets/js/theme.js' %}"></script>
    <script src="{% static 'assets/js/coustom.js' %}"></script>
    <script src="{% static 'assets/js/jquery.fancybox.js' %}"></script>
    <script src="{% static 'assets/js/jquery.barfiller.js' %}"></script>
    <script src="{% static 'assets/js/swiper-bundle.min.js' %}"></script>
    <script src="{% static 'assets/js/scrollCue.min.js' %}"></script>
    {% block js %} {% endblock %}
</body>

</html>

templates/partials/_footer.html
{% load static %} 
{% load i18n %}

    <div class="footer-area">
        <div class="container">
            <div class="row">
                <div class="col-lg-4 col-md-6 col-sm-6">
                    <div class="footer-widget-contact">
                        <div class="footer-widget-logo">
                            <a href="{% url 'base:index' %}"><img src="{{ navigation_item.footer_img.url }}" alt=""></a>
                        </div>
                        <div class="footer-widget-content">
                            <div class="footer-widget-title">
                                <h4>{% trans "Əlaqə məlumatları" %}</h4>
                            </div>
                            <div class="footer-widget-contact-info">
                                <ul>
                                    <li><i class="bi bi-telephone-fill"></i><a href="tel:{{ navigation_item.phone }}">{{ navigation_item.phone }}</a></li>
                                    <li><i class="bi bi-envelope"></i><a
                                            href="mailto:{{ navigation_item.email }}">{{ navigation_item.email }}</a></li>
                                    <li><i class="bi bi-geo-alt-fill"></i><a href="">{{ navigation_item.address }}</a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="footer-widget-social-icon">
                            <ul>

                                {% if navigation_item.facebook_link %}
                                    <li>
                                        <a href="{{ navigation_item.facebook_link }}"><i class="fab fa-facebook-f"></i></a>
                                    
                                    </li>
                                {% endif %}

                                {% if navigation_item.instagram_link %}
                                    <li>
                                        <a href="{{ navigation_item.instagram_link }}"><i class="fab fa-instagram"></i></a>
                                    
                                    </li>
                                {% endif %}

                                {% if navigation_item.whatsapp_number %}
                                    <li>
                                        <a href="https://api.whatsapp.com/send?phone={{ navigation_item.whatsapp_number }}"><i class="fab fa-whatsapp"></i></a>
                                    
                                    </li>
                                {% endif %}

                                {% if navigation_item.tiktok_link %}
                                    <li>
                                        <a href="{{ navigation_item.tiktok_link }}"><i class="fab fa-tiktok"></i></a>
                                    
                                    </li>
                                {% endif %}

                                {% if navigation_item.telegram_link %}
                                    <li>
                                        <a href="{{ navigation_item.telegram_link }}"><i class="fab fa-telegram"></i></a>
                                    
                                    </li>
                                {% endif %}

                                {% if navigation_item.youtube_link %}
                                    <li>
                                        <a href="{{ navigation_item.youtube_link }}"><i class="fab fa-youtube"></i></a>
                                    </li>
                                {% endif %}

                                {% if navigation_item.twitter_link %}
                                    <li>
                                        <a href="{{ navigation_item.twitter_link }}"><i class="fab fa-twitter"></i></a>
                                    </li>
                                {% endif %}
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6 col-sm-6">
                    <div class="footer-widget-content upper">
                        <div class="footer-widget-title">
                            <h4>{% trans "Keçidlər" %}</h4>
                        </div>
                        <div class="footer-widget-menu">
                            <ul>
                                <li><a href="{% url 'base:index' %}">{% trans "Ana səhifə" %}</a></li>
                                <li><a href="{% url 'base:about' %}">{% trans "Haqqımızda" %}</a></li>
                                <li><a href="{% url 'base:index' %}#services">{% trans "Xidmətlərimiz" %}</a></li>
                                <li><a href="{% url 'room:rooms' %}">{% trans "Otaqlarımız" %}</a></li>
                                <li><a href="{% url 'blog:blogs' %}">{% trans "Bloq" %}</a></li>
                                <li><a href="{% url 'contact:contact' %}">{% trans "Əlaqə" %}</a></li>
                            </ul>
                        </div>
                    </div>
                </div>

                <div class="col-lg-4 col-md-6 col-sm-6">
                    <div class="footer-widget-content">
                        <div class="footer-widget-title">
                            <h4>{% trans "Abonəlik" %}</h4>
                        </div>
                        <div class="single-newsletter-box">
                            <form action="{% url 'base:index' %}" method="post" class="form-horizontal">
                                {% csrf_token %}
                                {{ form.email }}
                                <button type="submit">{% trans "Abone ol" %}</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="footer-bottom-area">
        <div class="container">
            <div class="row">
                <div class="col-md-12 text-center">
                    <div class="footer-bottom-content">
                        <h4>© <a href="{% url 'base:index' %}">Quba Vadi</a>. {% trans "Bütün hüquqlar qorunur." %}</h4>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="curser"></div>
    <div class="curser2"></div>

    <div class="prgoress_indicator active-progress">
        <svg class="progress-circle svg-content" width="100%" height="100%" viewBox="-1 -1 102 102">
            <path d="M50,1 a49,49 0 0,1 0,98 a49,49 0 0,1 0,-98"
                style="transition: stroke-dashoffset 10ms linear 0s; stroke-dasharray: 307.919, 307.919; stroke-dashoffset: 270.456;">
            </path>
        </svg>
    </div>

templates/partials/_navbar.html
{% load static %}
{% load i18n %}

<div class="dark">
    <div class="dark-button">
        <input type="checkbox" class="toggle-switch">
    </div>
</div>

<div class="header-area" id="sticky-header">
    <div class="container-fulid">
        <div class="row align-items-center">
            <div class="col-lg-3">
                <div class="header-logo">
                    <a href="{% url 'base:index' %}"><img src="{{ navigation_item.navbar_img.url }}" alt=""></a>
                </div>
            </div>
            <div class="col-lg-7">
                <div class="header-menu">
                    <ul>
                        <li class=""><a href="{% url 'base:index' %}">{% trans "Ana səhifə" %}</a></li>
                        <li><a href="{% url 'base:about' %}">{% trans "Haqqımızda" %}</a></li>
                        <li class="menu-item-has-children">
                            <a href="{% url 'room:rooms' %}">{% trans "Otaqlarımız" %}<i class="fas fa-chevron-down"></i></a>
                            <ul class="sub-menu">
                                {% for category in categories %}
                                    <li>
                                        <a href="{% url 'room:rooms' %}?category={{ category.slug }}">{{ category.name }}</a>
                                    </li>
                                {% endfor %}
                            </ul>
                        </li>
                        <li class="menu-item-has-children">
                            <a href="{% url 'base:index' %}#services">{% trans "Xidmətlərimiz" %}<i class="fas fa-chevron-down"></i></a>
                            <ul class="sub-menu">
                                {% for service in services %}
                                    <li>
                                        <a href="{% url 'service:service_details' service.slug %}">{{ service.title }}</a>
                                    </li>
                                {% endfor %}
                            </ul>
                        </li>
                        <li><a href="{% url 'blog:blogs' %}">{% trans "Bloq" %}</a></li>
                        <li><a href="{% url 'contact:contact' %}">{% trans "Əlaqə" %}</a></li>
                        <li class="menu-item-has-children language-li">
                            <a href="{% url 'base:set-language' 'az' %}">Az<i class="fas fa-chevron-down"></i></a>
                            <ul class="sub-menu">
                                <li><a href="{% url 'base:set-language' 'ru' %}">Ru</a></li>
                                <li><a href="{% url 'base:set-language' 'en' %}">En</a></li>
                                <li><a href="{% url 'base:set-language' 'ar' %}">Arab</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
            {% if not user.is_authenticated %}
                <div class="col-lg-2">
                    <div class="header-button text-right">
                        <a href=" {% url 'user:register' %}">{% trans "Qeydiyyat" %}</a>
                    </div>
                </div>
            {% else %}
                <div class="col-lg-2">
                    <div class="header-button text-right">
                        <a href="{% url 'user:account' %}">{{ user.first_name }} {{ user.last_name }}</a>
                    </div>
                </div>
            {% endif %}
        </div>
    </div>
</div>

<div class="mobile-menu-area sticky d-sm-block d-md-block d-lg-none ">
    <img src="{{ navigation_item.navbar_img.url }}" alt="">
    <li class="mobile-lang">
        <a href=" {% url 'user:register' %}" class="user"><i class="fas fa-user"></i></a>
        <div class="lang-user">
            <a href="{% url 'base:set-language' 'az' %}" class="selected-lang">Az<i class="fas fa-chevron-down"></i></a>
            <ul class="sub-menu">
                <li><a href="{% url 'base:set-language' 'ru' %}">Ru</a></li>
                <li><a href="{% url 'base:set-language' 'en' %}">En</a></li>
                <li><a href="{% url 'base:set-language' 'ar' %}">Arab</a></li>
            </ul>
        </div>
    </li>
    <div class="mobile-menu">
        <nav class="header-menu">
            <ul class="nav_scroll">
                <li>
                    <a href="{% url 'base:index' %}">{% trans "Ana səhifə" %}</a>
                </li>
                <li><a href="{% url 'base:about' %}">{% trans "About" %}</a></li>
                <li class="menu-item-has-children"><a href="{% url 'room:rooms' %}">{% trans "Otaqlarımız" %}</a>
                    <ul class="sub-menu">
                        {% for category in categories %}
                            <li>
                                <a href="{% url 'room:rooms' %}?category={{ category.slug }}">{{ category.name }}</a>
                            </li>
                        {% endfor %}
                    </ul>
                </li>
                <li class="menu-item-has-children"><a href="{% url 'base:index' %}#services">{% trans "Xidmətlərimiz" %}</a>
                    <ul class="sub-menu">
                        {% for service in services %}
                            <li>
                                <a href="{% url 'service:service_details' service.slug %}">{{ service.title }}</a>
                            </li>
                        {% endfor %}
                    </ul>
                </li>
                <li><a href="{% url 'blog:blogs' %}">{% trans "Blog" %}</a></li>
                <li><a href="{% url 'contact:contact' %}">{% trans "Contact" %}</a></li>
            </ul>
        </nav>
    </div>
</div>