base/urls.py
from django.urls import path
from .views import *

app_name = 'base'

urlpatterns = [
    path('', index, name='index'),
    path('about/', about, name='about'),
    path("set_language/<str:language>", set_language, name="set-language"),
]

blog/urls.py
from django.urls import path
from .views import *

app_name = 'blog'

urlpatterns = [
    path('', blogs, name='blogs'),
    path('<slug:blog_slug>', blog_details, name='blog_details'),
]

core/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += i18n_patterns(
    path('', include('base.urls', namespace='base')),
    path('rooms/', include('room.urls', namespace='room')),
    path('services/', include('service.urls', namespace='service')),
    path('blogs/', include('blog.urls', namespace='blog')),
    path('contact/', include('contact.urls', namespace='contact')),
    path('user/', include('user.urls', namespace='user')),
    path('rosetta/', include('rosetta.urls')),
    prefix_default_language=False,
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

room/urls.py
from django.urls import path
from .views import *

app_name = 'room'

urlpatterns = [
    path('', rooms, name='rooms'),
    path('<slug:room_slug>/', room_details, name='room-details')
]

user/urls.py
from django.urls import path
from .views import *

app_name = 'user'

urlpatterns = [
    path('login/', login_view, name='login'),
    path('register/', register, name='register'),
    path('logout/', logout_view, name='logout'),
    path('account/', account, name='account'),
    path('change-password/', change_password, name='change-password'),
    path('payment/', payment, name='payment'),
    path('send-email-code/', send_email_code, name='send-email-code'),
    path('six-digit-password/', six_digit_password, name='six-digit-password'),
]

blog/models.py
from django.db import models
from django.utils.text import slugify

class BlogCategory(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(unique=True, blank=True)
    
    def save(self, *args, **kwargs):
        if not self.slug or self.slug != slugify(self.name):
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)
         
    def __str__(self):
        return self.name
    
    

class Blog(models.Model):
    title = models.CharField(max_length=200, verbose_name='Blog Başlığı')
    description = models.TextField()
    image = models.ImageField(upload_to='blog_images/')
    category = models.ForeignKey(BlogCategory, on_delete=models.CASCADE, related_name='blogs')
    slug = models.SlugField(unique=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def save(self, *args, **kwargs):
        if not self.slug or self.slug != slugify(self.title):
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)
         
    def __str__(self):
        return self.title
    
    
class BlogImages(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name='images')
    image = models.ImageField(upload_to='blog_images/')

    def __str__(self):
        return f"Image for {self.blog.title}"

contact/models.py
from django.db import models
from room.models import Room

class Contact(models.Model):
    name = models.CharField(max_length=100, verbose_name="Ad")
    phone = models.CharField(max_length=15, verbose_name="Telefon")
    email = models.EmailField(verbose_name="Email Ünvanı")
    room = models.ForeignKey(Room, on_delete=models.CASCADE, related_name="contacts", verbose_name="Otaq")
    message = models.TextField(blank=True, null=True, verbose_name="Mesaj")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Göndərilmə Tarixi")

    def __str__(self):
        return f"{self.name} ({self.email})"

room/models.py
from django.db import models
from django.utils.text import slugify

class RoomCategory(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(unique=True, blank=True)

    def save(self, *args, **kwargs):
        if not self.slug or self.slug != slugify(self.name):
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name_plural = 'Room Categories'


class Room(models.Model):
    category = models.ForeignKey(RoomCategory, on_delete=models.CASCADE)
    number = models.IntegerField()
    name = models.CharField(max_length=200)
    description = models.TextField()
    image = models.ImageField(upload_to='room_images/', null=True, blank=True)
    mature_capacity = models.IntegerField()
    young_capacity = models.IntegerField()
    bed_position = models.CharField(max_length=100, null=True, blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    discount_price = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    owner_number = models.CharField(max_length=50, null=True, blank=True)
    enter_time = models.TimeField()
    exit_time = models.TimeField()
    star_number = models.IntegerField()
    slug = models.SlugField(unique=True, blank=True)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        if not self.slug or self.slug != slugify(self.name):
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.name} - {self.number}"
    
    class Meta:
        verbose_name_plural = 'Rooms'
    
    
class RoomImage(models.Model):
    room = models.ForeignKey(Room, on_delete=models.CASCADE, related_name='images')
    image = models.ImageField(upload_to='room_images/')

    def __str__(self):
        return f"Image for {self.room.name}"
    

class RoomSupply(models.Model):
    room = models.ForeignKey(Room, on_delete=models.CASCADE, related_name='supplies')
    name = models.CharField(max_length=100)
    icon = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.name} for {self.room.name}"
    
    
class RoomFeature(models.Model):
    room = models.ForeignKey(Room, on_delete=models.CASCADE, related_name='features')
    name = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.name} for {self.room.name}"

service/models.py
from django.db import models
from django.utils.text import slugify

class Service(models.Model):
    title = models.CharField(max_length=100)
    icon = models.ImageField(upload_to='services_icon/')
    image = models.ImageField(upload_to='services/')
    slug = models.SlugField(unique=True, blank=True)

    def save(self, *args, **kwargs):
        if not self.slug or self.slug != slugify(self.title):
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title
    
    
class ServiceImage(models.Model):
    service = models.ForeignKey(Service, on_delete=models.CASCADE, related_name='images')
    image = models.ImageField(upload_to='services_images/')

    def __str__(self):
        return self.service.title


class ServiceVideo(models.Model):
    service = models.ForeignKey(Service, on_delete=models.CASCADE, related_name='videos')
    video_url = models.URLField(null=True, blank=True)

    def __str__(self):
        return self.service.title

contact/forms.py
from django import forms
from .models import Contact

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ['name', 'phone', 'email', 'room', 'message']
        widgets = {
            'name': forms.TextInput(attrs={
                'placeholder': 'Ad', 
                'class': 'form-control'
            }),
            'phone': forms.TextInput(attrs={
                'placeholder': 'Telefon', 
                'class': 'form-control'
            }),
            'email': forms.EmailInput(attrs={
                'placeholder': 'Email ünvanınız', 
                'class': 'form-control'
            }),
            'room': forms.Select(attrs={
                'class': 'form-control',
            }),
            'message': forms.Textarea(attrs={
                'placeholder': 'Mesaj yazın', 
                'class': 'form-control',
                'rows': 4
            }),
        }
        labels = {
            'name': 'Ad',
            'phone': 'Telefon',
            'email': 'Email Ünvanınız',
            'room': 'Otaq seçin',
            'message': 'Mesaj'
        }

    def save(self, commit=True):
        instance = super().save(commit=False)
        room_id = self.cleaned_data.get('room')
        if room_id:
            instance.room = room_id
        if commit:
            instance.save()
        return instance

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import BlogCategory, Blog
from django.core.paginator import Paginator
from django.db.models import Q


def blogs(request):
    
    category_slug = request.GET.get('category')
    search_query = request.GET.get('search', '')
    blogs = Blog.objects.all().order_by('-created_at')
    
    if category_slug:
        category = BlogCategory.objects.filter(slug=category_slug).first()
        blogs = blogs.filter(category=category) if category else Blog.objects.none()

    if search_query:
        blogs = blogs.filter(
            Q(title__icontains=search_query) | Q(description__icontains=search_query)
        )
    
    blog_categories = BlogCategory.objects.all()
    
    paginator = Paginator(blogs, 6)
    page_number = request.GET.get('page', 1)
    page_obj = paginator.get_page(page_number)
    
    context = {
        'page_obj': page_obj,
        'selected_category': category_slug,
        'search_query': search_query,
        'blog_categories' : blog_categories
    }
    
    return render(request, 'blogs.html', context)


def blog_details(request, blog_slug):
    
    blog = get_object_or_404(Blog, slug=blog_slug)
    blog_categories = BlogCategory.objects.all()
    
    context = {
        'blog' : blog,
        'blog_categories' : blog_categories
    }
    return render(request, 'blog-details.html', context)

contact/views.py
from django.shortcuts import render, redirect
from .forms import ContactForm
from room.models import Room

def contact(request):
    rooms = Room.objects.all()
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('contact:contact')
    else:
        form = ContactForm()

    return render(request, 'contact.html', {
        'form': form,
        'rooms': rooms
    })

room/views.py
from django.shortcuts import render, get_object_or_404
from .models import *
from django.core.paginator import Paginator
from django.db.models import Q

def rooms(request):
    
    category_slug = request.GET.get('category')
    search_query = request.GET.get('search', '')
    rooms = Room.objects.all().order_by('-created_at')
    
    if category_slug:
        category = RoomCategory.objects.filter(slug=category_slug).first()
        rooms = rooms.filter(category=category) if category else Room.objects.none()

    if search_query:
        rooms = rooms.filter(
            Q(name__icontains=search_query) | Q(number__icontains=search_query) | Q(description__icontains=search_query)
        )
    
    paginator = Paginator(rooms, 16)
    page_number = request.GET.get('page', 1)
    page_obj = paginator.get_page(page_number)
    
    context = {
        'page_obj': page_obj,
        'rooms' : rooms,
        'category_slug' : category_slug
    }
    
    return render(request, 'rooms.html', context)


def room_details(request, room_slug):
    
    room = get_object_or_404(Room, slug=room_slug)
    context = {
        'room' : room
    }
    
    return render(request, 'room-details.html', context)

service/views.py
from django.shortcuts import render, get_object_or_404
from .models import *

def service_details(request, service_slug):
    
    service = get_object_or_404(Service, slug=service_slug)
    
    context = {
        'service': service
    }
    return render(request, 'services.html', context)

templates/blog-details.html
{% extends "partials/_base.html" %}
{% load static %} 
{% load i18n %}

{% block title %} {{ blog.title }} {% endblock %}

{% block content %}

	<div class="breadcumb-area d-flex align-items-center"
		style="background-image: url({% static 'assets/images/inner/breadcumb.jpg' %});">
		<div class="container">
			<div class="row align-items-center">
				<div class="col-md-12">
					<div class="breacumb-content">
						<div class="breadcum-title">
							<h4>{{ blog.title }}</h4>
						</div>
						<ul>
							<li><a href="{% url 'base:index' %}">{% trans 'Ana Səhifə' %}</a></li>
							<li>/</li>
							<li>{{ blog.title }}</li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>

	<div class="blog-details-area">
		<div class="container">
			<div class="row">
				<div class="col-lg-8 col-md-12">
					<div class="row">
						<div class="room-details-content">
							<div class="row">
								<div class="room-details-list owl-carousel">
									<div class="col-lg-12">
										<div class="room-detils-thumb">
											<img src="{{ blog.image.url }}" alt="{{ blog.title }}">
										</div>
									</div>
								</div>
							</div>

							<h1>{{ blog.title }}</h1>
							<p class="room-detils-desc">{{ blog.description|linebreaks }}</p>
						</div>
						<div class="blog-area blog-related-area">
							<div class="row post-items-style3">
                                {% for item in blog.images.all %}
                                    <div class="col-lg-4 col-md-6 col-6">
                                        <div class="single_related">
                                            <div class="related_thumb">
                                                <a href="{{ item.image.url }}" data-fancybox="blog-images">
                                                    <img src="{{ item.image.url }}" alt="">
                                                    <span class="zoom-icon"><i class="fa fa-search"></i></span>
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                {% endfor %}
							</div>
						</div>
					</div>
				</div>
				<div class="col-lg-4">
					<div class="row">
						<div class="col-lg-12">
							<div class="widget-categories-box">
								<div class="categories_title">
									<h4>{% trans 'Ən məşhur postlar' %} </h4>
								</div>
                                {% for blog in last_blogs %}
                                    <div class="sidber-widget-recent-post">
                                        <div class="recent-widget-thumb">
                                            <img src="{{ blog.image.url }}" alt="{{ blog.title }}">
                                        </div>
                                        <div class="recent-widget-content">
                                            <a href="{% url 'blog:blog_details' blog.slug %}">{{ blog.title }}</a>
                                            <p> {{ blog.created_at|date:"M d, Y h:i A" }}</p>
                                        </div>
                                    </div>
                                {% endfor %}
							</div>
							<div class="widget-categories-box">
								<div class="categories_title">
									<h4>{% trans 'Kateqoriyalar' %} </h4>
								</div>
								<div class="widget-catefories-list">
									<ul>
                                        {% for item in blog_categories %}
										    <li>
                                                <a href="#"><i class="fas fa-angle-double-right"></i>{{ item.name }}</a>
                                            </li>
                                        {% endfor %}
									</ul>
								</div>
							</div>

						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

	<div class="brand-area">
		<div class="container">
			<div class="row">
				<div class="col-lg-4"></div>
				<div class="col-lg-8">
					<div class="row">
                        <div class="brand-list owl-carousel">
                            {% for brand in brands %}
                                <div class="col-lg-12">
                                    <div class="single-brand-box">
                                        <div class="brand-thumb">
                                            <img src="{{ brand.image.url }}" alt="{{ brand.name }}">
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
				</div>
			</div>
		</div>
	</div>

{% endblock %}

templates/blogs.html
{% extends "partials/_base.html" %}
{% load static %} 
{% load i18n %}

{% block title %} {% trans 'Bloglar' %} {% endblock %}

{% block content %}

	<div class="breadcumb-area d-flex align-items-center"
		style="background-image: url({% static 'assets/images/inner/breadcumb.jpg' %});">
		<div class="container">
			<div class="row align-items-center">
				<div class="col-md-12">
					<div class="breacumb-content">
						<div class="breadcum-title">
							<h4>{% trans 'Blog' %}</h4>
						</div>
						<ul>
							<li><a href="{% url 'base:index' %}">{% trans 'Ana Səhifə' %}</a></li>
							<li>/</li>
							<li>{% trans 'Blog' %}</li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>

	<div class="blog-details-area">
		<div class="container">
			<div class="row">
				<div class="col-lg-8">
					<div class="row">
                        {% if page_obj %}
                            {% for blog in page_obj %}
                                <div class="col-lg-6 col-md-6">
                                    <div class="single-blog-box inner">
                                        <div class="single-blog-thumb">
                                            <a href="{% url 'blog:blog_details' blog.slug %}"> <img src="{{ blog.image.url }}" alt="{{ blog.title }}"></a>
                                        </div>
                                        <div class="blog-content">
                                            <div class="meta-blog">
                                                <span>{{ blog.created_at|date:"F d, Y" }}</span>
                                                <span>{{ blog.category.name }}</span>
                                            </div>
                                            <a href="{% url 'blog:blog_details' blog.slug %}">{{ blog.title }}</a>
                                        </div>
                                        <div class="blog-button">
                                            <a href="{% url 'blog:blog_details' blog.slug %}">{% trans 'Daha çox' %}<span><i class="bi bi-arrow-right"></i></span></a>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        {% else %}
                            <div class="alert alert-warning" role="alert">
                                {% trans 'Hələ blog əlavə olunmayıb' %}
                            </div>
                        {% endif %}
					</div>

					<div class="pagination-area">
                        <div thumbsSlider="" class="swiper mySwiper th-pagination">
                            <div class="swiper-wrapper">
                                {% if page_obj.has_previous %}
                                    <div class="swiper-slide">
                                        <li><a href="?page={{ page_obj.previous_page_number }}"><i class="fa-solid fa-chevron-left"></i></a></li>
                                    </div>
                                {% else %}
                                    <div class="swiper-slide">
                                        <li class="disabled"><a><i class="fa-solid fa-chevron-left"></i></a></li>
                                    </div>
                                {% endif %}
                    
                                {% for page_num in page_obj.paginator.page_range %}
                                    <div class="swiper-slide">
                                        <li>
                                            {% if page_num == page_obj.number %}
                                                <a class="active" href="?page={{ page_num }}">{{ page_num }}</a>
                                            {% else %}
                                                <a href="?page={{ page_num }}">{{ page_num }}</a>
                                            {% endif %}
                                        </li>
                                    </div>
                                {% endfor %}
                    
                                {% if page_obj.has_next %}
                                    <div class="swiper-slide">
                                        <li><a href="?page={{ page_obj.next_page_number }}"><i class="fa-solid fa-chevron-right"></i></a></li>
                                    </div>
                                {% else %}
                                    <div class="swiper-slide">
                                        <li class="disabled"><a><i class="fa-solid fa-chevron-right"></i></a></li>
                                    </div>
                                {% endif %}
                            </div>
                        </div>
                    </div>

				</div>
				<div class="col-lg-4">
					<div class="row">
						<div class="col-lg-12">
							<div class="widget_search">
                                <form method="get" action="{% url 'blog:blogs' %}">
                                    <div class="form-group">
                                        <input type="search" name="search" placeholder="Burada axtar..." value="{{ search_query }}" required>
                                        <button type="submit" class="icons">
                                            <i class="fa fa-search"></i>
                                        </button>
                                    </div>
                                </form>
							</div>
							<div class="widget-categories-box">
								<div class="categories_title">
									<h4>Popular post </h4>
								</div>
                                {% for blog in last_blogs %}
                                    <div class="sidber-widget-recent-post">
                                        <div class="recent-widget-thumb">
                                            <img src="{{ blog.image.url }}" alt="{{ blog.title }}">
                                        </div>
                                        <div class="recent-widget-content">
                                            <a href="{% url 'blog:blog_details' blog.slug %}">{{ blog.title }}</a>
                                            <p> {{ blog.created_at|date:"M d, Y h:i A" }}</p>
                                        </div>
                                    </div>
                                {% endfor %}
							</div>
							<div class="widget-categories-box">
								<div class="categories_title">
									<h4>Kateqoriyalar </h4>
								</div>
								<div class="widget-catefories-list">
									<ul>
                                        {% for item in blog_categories %}
										    <li>
                                                <a href="{% url 'blog:blogs' %}?category={{ item.slug }}"><i class="fas fa-angle-double-right"></i>{{ item.name }}</a>
                                            </li>
                                        {% endfor %}
									</ul>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>

		</div>
	</div>

	<div class="brand-area">
		<div class="container">
			<div class="row">
				<div class="col-lg-4"></div>
				<div class="col-lg-8">
					<div class="row">
                        <div class="brand-list owl-carousel">
                            {% for brand in brands %}
                                <div class="col-lg-12">
                                    <div class="single-brand-box">
                                        <div class="brand-thumb">
                                            <img src="{{ brand.image.url }}" alt="{{ brand.name }}">
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
				</div>
			</div>
		</div>
	</div>

{% endblock %}

{% block js %}

    <script>

        document.addEventListener('DOMContentLoaded', function () {
            var swiperThumbs = new Swiper(".mySwiper", {
                spaceBetween: 10,
                slidesPerView: 5,
                freeMode: true,
                watchSlidesProgress: true,
                navigation: {
                    nextEl: ".swiper-button-next-thumbs",
                    prevEl: ".swiper-button-prev-thumbs",
                },
                breakpoints: {
                    576: {
                        slidesPerView: 5, // Small tablets
                    },
                    768: {
                        slidesPerView: 6, // Small tablets
                    },
                    992: {
                        slidesPerView: 6, // Large tablets
                    },
                    1200: {
                        slidesPerView: 5, // Desktop
                    },
                },
                on: {
                    init: function () {
                        toggleNavigationButtons(this);
                    },
                    resize: function () {
                        toggleNavigationButtons(this);
                    },
                }
            });


            function toggleNavigationButtons(swiper) {
                // Ensure swiper has fully initialized before querying slides
                setTimeout(() => {
                    const totalSlides = swiper.slides.length;
                    const visibleSlides = swiper.params.slidesPerView;

                    const nextButton = document.querySelector(".swiper-button-next");
                    const prevButton = document.querySelector(".swiper-button-prev");

                    if (nextButton && prevButton) {

                        if (totalSlides <= visibleSlides) {
                            nextButton.classList.add('dnone');
                            prevButton.classList.add('dnone');
                            nextButton.style.display = 'none';
                            prevButton.style.display = 'none';
                        } else {
                            nextButton.style.display = 'block';
                            prevButton.style.display = 'block';
                        }
                    } else {
                        console.error('Navigation buttons not found');
                    }
                }, 100); // Added a bit more delay to ensure proper rendering
            }
        });


    </script>

{% endblock %}