base/urls.py
from django.urls import path
from .views import *

app_name = 'base'

urlpatterns = [
    path('', index, name='index'),
    path('about/', about, name='about'),
    path("set_language/<str:language>", set_language, name="set-language"),
]

core/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += i18n_patterns(
    path('', include('base.urls', namespace='base')),
    path('rooms/', include('room.urls', namespace='room')),
    path('services/', include('service.urls', namespace='service')),
    path('blogs/', include('blog.urls', namespace='blog')),
    path('contact/', include('contact.urls', namespace='contact')),
    path('user/', include('user.urls', namespace='user')),
    path('rosetta/', include('rosetta.urls')),
    prefix_default_language=False,
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from .views import *

app_name = 'user'

urlpatterns = [
    path('login/', login_view, name='login'),
    path('register/', register, name='register'),
    path('logout/', logout_view, name='logout'),
    path('account/', account, name='account'),
    path('change-password/', change_password, name='change-password'),
    path('payment/', payment, name='payment'),
    path('send-email-code/', send_email_code, name='send-email-code'),
    path('six-digit-password/', six_digit_password, name='six-digit-password'),
]

user/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import AuthenticationForm

from django import forms
from django.core.exceptions import ValidationError

class RegisterForm(forms.Form):
    first_name = forms.CharField(
        max_length=100, 
        required=True, 
        label="Ad",
        widget=forms.TextInput(attrs={'placeholder': 'Ad', 'class': 'form-control'})
    )
    last_name = forms.CharField(
        max_length=100, 
        required=True, 
        label="Soyad",
        widget=forms.TextInput(attrs={'placeholder': 'Soyad', 'class': 'form-control'})
    )
    email = forms.EmailField(
        required=True, 
        label="E-poçt", 
        widget=forms.EmailInput(attrs={'placeholder': 'E-poçt ünvanı', 'class': 'form-control'})
    )
    phone_number = forms.CharField(
        max_length=14, 
        required=True, 
        label="Telefon nömrəsi",
        widget=forms.TextInput(attrs={'placeholder': 'Telefon nömrəsi', 'class': 'form-control'})
    )
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'placeholder': 'Şifrə', 'class': 'form-control'}),
        required=True, 
        label="Şifrə"
    )
    confirm_password = forms.CharField(
        widget=forms.PasswordInput(attrs={'placeholder': 'Təkrar şifrə', 'class': 'form-control'}),
        required=True, 
        label="Təkrar şifrə"
    )

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')

        if password != confirm_password:
            raise ValidationError("Şifrələr uyğun gəlmir.")
        return cleaned_data

class LoginForm(forms.Form):
    email = forms.EmailField(
        label="Email", 
        widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Email'})
    )
    password = forms.CharField(
        label="Şifrə", 
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Şifrə'})
    )

user/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib import messages
from .forms import RegisterForm, LoginForm
from django.contrib.auth import authenticate, login, logout

def login_view(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            
            user = authenticate(request, username=email, password=password)
            if user is not None:
                login(request, user)
                return redirect('base:index')
            else:
                messages.error(request, 'Daxil edilmiş məlumatlar yanlışdır.')
        else:
            messages.error(request, 'Formada səhv var.')
    else:
        form = LoginForm()

    return render(request, 'user/login.html', {'form': form})

def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            email = form.cleaned_data['email']
            phone_number = form.cleaned_data['phone_number']
            password = form.cleaned_data['password']
            
            user = User.objects.create_user(
                username=email,
                first_name=first_name,
                last_name=last_name,
                email=email,
                password=password
            )
            
            user.phone_number = phone_number
            user.save()

            messages.success(request, 'Qeydiyyat uğurla tamamlandı!')
            return redirect('user:login')
    else:
        form = RegisterForm()
    
    return render(request, 'user/register.html', {'form': form})


def logout_view(request):
    logout(request)
    return redirect('user:login')


def account(request):
    return render(request, 'user/account.html')


def change_password(request):
    return render(request, 'user/changePassword.html')


def payment(request):
    return render(request, 'payment.html')


def send_email_code(request):
    return render(request, 'user/sendEmailCode.html')


def six_digit_password(request):
    return render(request, 'user/sixdigitsPassword.html')

templates/user/account.html
{% extends "partials/_base.html" %}
{% load static %} 
{% load i18n %}

{% block title %} {% trans 'Hesabım' %} {% endblock %}

{% block css %}

    <style>
        .styled-table {
            width: 100%;
            border-collapse: collapse;
            margin: 25px 0;
            font-size: 18px;
            text-align: left;
        }

        .styled-table thead tr {
            background-color: #c19d68;
            color: #fff;
            text-align: center;
        }

        .styled-table th,
        .styled-table td {
            padding: 12px 15px;
            border: 1px solid #c19d68;
        }

        .styled-table tbody tr {
            border-bottom: 1px solid #c19d68;
        }

        .styled-table tbody tr:nth-of-type(even) {
            background-color: #f3f3f3;
        }

        .styled-table tbody tr:hover {
            background-color: #f6efe2;
        }

        .styled-table tbody tr:last-of-type {
            border-bottom: 2px solid #c19d68;
        }

        /* Responsive Styles */
        .table-responsive {
            overflow-x: auto;
        }

        .logout a {
            display: inline-block;
            font-size: 16px;
            text-transform: uppercase;
            color: #ffffff;
            font-weight: 500;
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            border: 1px solid #fff;
            padding: 11px 27px;
            position: relative;
            z-index: 1;
            transition: 0.5s;
            background-color: #c19d68;
            margin-top: 15px;
            border: 1px solid #c19d68;;
        }
        

        @media (max-width: 768px) {

            .styled-table th,
            .styled-table td {
                font-size: 16px;
                padding: 10px;
            }
        }

        @media (max-width: 576px) {

            .styled-table th,
            .styled-table td {
                font-size: 14px;
                padding: 8px;
            }

            .styled-table {
                width: 100%;
                border-collapse: collapse;
                margin: 5px 0;
                font-size: 18px;
                text-align: left;
            }
        }
    </style>

{% endblock %}


{% block content %}

    <main>

        <div class="breadcumb-area d-flex align-items-center"
            style="background-image: url({% static 'assets/images/inner/breadcumb.jpg' %});">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-md-12">
                        <div class="breacumb-content">
                            <div class="breadcum-title">
                                <h4>{{ user.first_name }} {{ user.last_name }}</h4>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <section class="after-none contact-bg pt-30 pb-140 p-relative fix">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-10">
                        <table class="styled-table">
                            <thead>
                                <tr>
                                    <th>{% trans "№" %}</th>
                                    <th>{% trans "Bron edilmiş otaq" %}</th>
                                    <th>{% trans "Qiyməti" %}</th>
                                    <th>{% trans "Tarixlər" %}</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>1</td>
                                    <td>{% trans "Standart otaq 405" %}</td>
                                    <td>150 ₼</td>
                                    <td>2024.12.20 - 2024.12.24</td>
                                </tr>
                                <tr>
                                    <td>2</td>
                                    <td>{% trans "Vip otaq" %}</td>
                                    <td>200 ₼</td>
                                    <td>2024.12.21 - 2024.12.24</td>
                                </tr>
                                <tr>
                                    <td>3</td>
                                    <td>{% trans "Connection otaq" %}</td>
                                    <td>250 ₼</td>
                                    <td>2024.12.22 - 2024.12.25</td>
                                </tr>
                            </tbody>
                        </table>
                        <div class="logout">
                            <a href="{% url 'user:logout' %}"><i class="fas fa-sign-out-alt"></i> {% trans "Çıxış et" %}</a>
                        </div>
                    </div>
                </div>
            </div>
        </section>

    </main>

{% endblock %}

{% block js %}
    
    <script>

        let passwordInputs = document.querySelectorAll('input[type="password"]')
        let iconHolders = document.querySelectorAll('.icon-holder')

        iconHolders.forEach(iconHolders => {

            iconHolders.addEventListener('click', function () {
                let passwordInput = this.previousElementSibling

                let icon = this.querySelector('i')
                if (passwordInput.type === 'password') {
                    passwordInput.type = 'text'
                    icon.classList.remove('fa-eye-slash')
                    icon.classList.add('fa-eye')
                }
                else {
                    passwordInput.type = 'password'
                    icon.classList.add('fa-eye-slash')
                    icon.classList.remove('fa-eye')
                }

            })
        })
    </script>

{% endblock %}

templates/user/changePassword.html
{% extends "partials/_base.html" %}
{% load static %} 
{% load i18n %}

{% block title %} {% trans 'Şifrə Yeniləmə' %} {% endblock %}

{% block content %}

    <main>

        <div class="breadcumb-area d-flex align-items-center" style="background-image: url({% static 'assets/images/inner/breadcumb.jpg' %});">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-md-12">
                        <div class="breacumb-content">
                            <div class="breadcum-title">
                                <h4>{% trans "Yeni şifrə" %}</h4>
                            </div>
                            <ul>
                                <li><a href="{% url 'base:index' %}">{% trans "Ana səhifə" %}</a></li>
                                <li>/</li>
                                <li>{% trans "Yeni şifrə" %}</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <section class="after-none contact-bg pt-50 pb-140 p-relative fix">
            <div class="container">

                <div class="row justify-content-center ">

                    <div class="col-lg-5">
                        <div class="contact-bg02 ">
                            <div class="section-title center-align mb-40 text-center wow fadeInDown animated"
                                data-animation="fadeInDown" data-delay=".4s">
                                <h2>{% trans "Yeni şifrəni yaz" %}</h2>
                            </div>
                            <form action="#" class="register-form mt-20">
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="input-field">
                                            <input type="password" name="password" placeholder="{% trans 'Şifrə *' %}">
                                            <div class="icon-holder">
                                                <i class="fa fa-eye-slash" aria-hidden="true"></i>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-12">
                                        <div class="input-field">
                                            <input type="password" name="password" placeholder="{% trans 'Təkrar şifrə *' %}">
                                            <div class="icon-holder">
                                                <i class="fa fa-eye-slash" aria-hidden="true"></i>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="row d-flex align-items-center form-bottom">
                                        <div class="col-lg-12">
                                            <div class="slider-btn">
                                                <button class="" type="submit"><span>{% trans 'Təsdiqlə' %}</span></button>
                                            </div>
                                        </div>

                                    </div>

                                </div>
                            </form>
                        </div>

                    </div>
                </div>

            </div>

        </section>

    </main>

{% endblock %}

{% block js %}
    
    <script>

        let passwordInputs = document.querySelectorAll('input[type="password"]')
        let iconHolders = document.querySelectorAll('.icon-holder')

        iconHolders.forEach(iconHolders => {

            iconHolders.addEventListener('click', function () {
                let passwordInput = this.previousElementSibling

                let icon = this.querySelector('i')
                if (passwordInput.type === 'password') {
                    passwordInput.type = 'text'
                    icon.classList.remove('fa-eye-slash')
                    icon.classList.add('fa-eye')
                }
                else {
                    passwordInput.type = 'password'
                    icon.classList.add('fa-eye-slash')
                    icon.classList.remove('fa-eye')
                }

            })
        })
    </script>

{% endblock %}

templates/user/login.html
{% extends "partials/_base.html" %}
{% load static %} 
{% load i18n %}

{% block title %} {% trans 'Giriş' %} {% endblock %}

{% block content %}

    <main>

        <div class="breadcumb-area d-flex align-items-center"
            style="background-image: url({% static 'assets/images/inner/breadcumb.jpg' %});">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-md-12">
                        <div class="breacumb-content">
                            <div class="breadcum-title">
                                <h4>{% trans "Daxil ol" %}</h4>
                            </div>
                            <ul>
                                <li><a href="{% url 'base:index' %}">{% trans "Ana səhifə" %}</a></li>
                                <li>/</li>
                                <li>{% trans "Daxil ol" %}</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <section class="after-none contact-bg pt-30 pb-140 p-relative fix">
            <div class="container">

                <div class="row justify-content-center ">
                    <div class="col-lg-5">
                        <div class="contact-bg02 ">
                            <div class="center-align text-center wow fadeInDown animated" data-animation="fadeInDown"
                                data-delay=".4s">
                                <h2>{% trans "Daxil ol" %}</h2>
                            </div>
                            <form method="POST" class="register-form mt-20">
                                {% csrf_token %}
                                <div class="row">
                                    <div class="col-lg-12">
                                        <div class="input-field mb-3">
                                            <div class="contact-field p-relative c-subject">
                                                {{ form.email }}
                                            </div>
                                            {% if form.email.errors %}
                                                <div class="invalid-feedback">
                                                    {% for error in form.email.errors %}
                                                        <p>{{ error }}</p>
                                                    {% endfor %}
                                                </div>
                                            {% endif %}
                                        </div>
                                    </div>
                            
                                    <div class="col-md-12">
                                        <div class="input-field mb-3">
                                            <div class="contact-field p-relative c-subject">
                                                {{ form.password }}
                                            </div>
                                            {% if form.password.errors %}
                                                <div class="invalid-feedback">
                                                    {% for error in form.password.errors %}
                                                        <p>{{ error }}</p>
                                                    {% endfor %}
                                                </div>
                                            {% endif %}
                                            <div class="icon-holder">
                                                <i class="fa fa-eye-slash" aria-hidden="true"></i>
                                            </div>
                                        </div>
                                    </div>
                            
                                    <div class="col-md-12">
                                        <a href="{% url 'user:send-email-code' %}" class="forget-password">{% trans "Şifrəmi unutdum" %}</a>
                                    </div>
                            
                                    <div class="row d-flex align-items-center form-bottom">
                                        <div class="col-lg-5">
                                            <div class="slider-btn">
                                                <button type="submit" class="btn btn-primary"><span>{% trans "Daxil ol" %}</span></button>
                                            </div>
                                        </div>
                                        <div class="col-lg-7 col-md-7 col-sm-12">
                                            <div class="right">
                                                <h6><span>*</span>{% trans "Hesabınız yoxdur?" %}
                                                    <a href="{% url 'user:register' %}">{% trans "Qeydiyyatdan keç" %}</a>
                                                </h6>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </form>
                            
                        </div>
                    </div>
                </div>
            </div>
        </section>

    </main>

{% endblock %}

{% block js %}

    <script>

        let passwordInputs = document.querySelectorAll('input[type="password"]')
        let iconHolders = document.querySelectorAll('.icon-holder')

        iconHolders.forEach(iconHolders => {

            iconHolders.addEventListener('click', function () {
                let passwordInput = this.previousElementSibling

                let icon = this.querySelector('i')
                if (passwordInput.type === 'password') {
                    passwordInput.type = 'text'
                    icon.classList.remove('fa-eye-slash')
                    icon.classList.add('fa-eye')
                }
                else {
                    passwordInput.type = 'password'
                    icon.classList.add('fa-eye-slash')
                    icon.classList.remove('fa-eye')
                }

            })
        })
    </script>

{% endblock %}

templates/user/sendEmailCode.html
{% extends "partials/_base.html" %}
{% load static %} 
{% load i18n %}

{% block title %} {% trans 'Emailə kod göndər' %} {% endblock %}

{% block content %}

    <main>

        <div class="breadcumb-area d-flex align-items-center"
            style="background-image: url({% static 'assets/images/inner/breadcumb.jpg' %});">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-md-12">
                        <div class="breacumb-content">
                            <div class="breadcum-title">
                                <h4>{% trans "Şifrənin bərpası" %}</h4>
                            </div>
                            <ul>
                                <li><a href="{% url 'base:index' %}">{% trans "Ana səhifə" %}</a></li>
                                <li>/</li>
                                <li>{% trans "Şifrənin bərpası" %}</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <section class="after-none contact-bg pt-30 pb-140 p-relative fix">
            <div class="container">

                <div class="row justify-content-center ">

                    <div class="col-lg-5">
                        <div class="contact-bg02">
                            <div class="center-align text-center wow fadeInDown animated" data-animation="fadeInDown"
                                data-delay=".4s">
                                <h2>{% trans "Kod göndər" %}</h2>
                            </div>
                            <form action="#" class="register-form mt-20">
                                <div class="row">

                                    <div class="col-lg-12">
                                        <div class="contact-field p-relative c-subject ">
                                            <input type="text" id="email" name="email" placeholder="{% trans 'Email' %}">
                                        </div>
                                    </div>

                                    <div class="row d-flex align-items-center form-bottom">
                                        <div class="col-lg-5">
                                            <div class="slider-btn">
                                                <button class="" type="submit"><span>{% trans 'Göndər' %}</span></button>
                                            </div>
                                        </div>

                                    </div>

                                </div>
                            </form>
                        </div>

                    </div>
                </div>

            </div>

        </section>

    </main>

{% endblock %}

templates/user/sixdigitsPassword.html
{% extends "partials/_base.html" %}
{% load static %} 
{% load i18n %}

{% block title %} {% trans '6 rəqəmli kod' %} {% endblock %}

{% block content %}
    
    <main>

        <div class="breadcumb-area d-flex align-items-center"
            style="background-image: url{% static 'assets/images/inner/breadcumb.jpg' %};">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-md-12">
                        <div class="breacumb-content">
                            <div class="breadcum-title">
                                <h4>{% trans "Şifrənin bərpası" %}</h4>
                            </div>
                            <ul>
                                <li><a href="{% url 'base:index' %}">{% trans "Ana səhifə" %}</a></li>
                                <li>/</li>
                                <li>{% trans "Şifrənin bərpası" %}</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <section class="after-none contact-bg pt-30 pb-140 p-relative fix">
            <div class="container">
                <div class="row justify-content-center ">
                    <div class="col-lg-5">
                        <div class="contact-bg02">
                            <div class="center-align text-center wow fadeInDown animated" data-animation="fadeInDown"
                                data-delay=".4s">
                                <h2>{% trans "Kod daxil edin" %}</h2>
                            </div>
                            <form action="#" class="register-form mt-20">
                                <div class="row">
                                    <div class="col-lg-12">
                                        <div class="contact-field p-relative c-subject ">
                                            <input type="number" name="code" placeholder="{% trans 'Kodu yazın' %}">
                                        </div>
                                    </div>

                                    <div class="row d-flex align-items-center form-bottom">
                                        <div class="col-lg-5">
                                            <div class="slider-btn">
                                                <button class="" type="submit"><span>{% trans 'Göndər' %}</span></button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </section>

    </main>

{% endblock %}